// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqzrQytt1I2Hiz3FRjoGLAmQjIxopbC4o',
    appId: '1:443417237800:android:b2fc159e08ccbb098d181d',
    messagingSenderId: '443417237800',
    projectId: 'ict-hub-test',
    storageBucket: 'ict-hub-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3NK5X9od6esJMn-_8rR_b7MPuYLilb5c',
    appId: '1:443417237800:ios:92bfba1bb6d1dc188d181d',
    messagingSenderId: '443417237800',
    projectId: 'ict-hub-test',
    storageBucket: 'ict-hub-test.appspot.com',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBinjccF9U1EUBhvMJrOOkq5ea35bAZjHI',
    appId: '1:443417237800:web:363b9ba6b78116b78d181d',
    messagingSenderId: '443417237800',
    projectId: 'ict-hub-test',
    authDomain: 'ict-hub-test.firebaseapp.com',
    storageBucket: 'ict-hub-test.appspot.com',
    measurementId: 'G-8D7DLFPPTY',
  );

}